import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
// Use CJS resolver so pre-commit NODE_PATH is honored.
const js = require("@eslint/js");
const globals = require("globals");

const frappeGlobals = Object.fromEntries(
	[
		"frappe",
		"ui_styles",
		"Vue",
		"SetVueGlobals",
		"__",
		"repl",
		"Class",
		"locals",
		"cint",
		"cstr",
		"cur_frm",
		"cur_dialog",
		"cur_page",
		"cur_list",
		"cur_tree",
		"msg_dialog",
		"is_null",
		"in_list",
		"has_common",
		"posthog",
		"has_words",
		"validate_email",
		"open_web_template_values_editor",
		"validate_name",
		"validate_phone",
		"validate_url",
		"get_number_format",
		"format_number",
		"format_currency",
		"comment_when",
		"open_url_post",
		"toTitle",
		"lstrip",
		"rstrip",
		"strip",
		"strip_html",
		"replace_all",
		"flt",
		"precision",
		"CREATE",
		"AMEND",
		"CANCEL",
		"copy_dict",
		"get_number_format_info",
		"strip_number_groups",
		"print_table",
		"Layout",
		"web_form_settings",
		"$c",
		"$a",
		"$i",
		"$bg",
		"$y",
		"$c_obj",
		"refresh_many",
		"refresh_field",
		"toggle_field",
		"get_field_obj",
		"get_query_params",
		"unhide_field",
		"hide_field",
		"set_field_options",
		"getCookie",
		"getCookies",
		"get_url_arg",
		"md5",
		"$",
		"jQuery",
		"moment",
		"hljs",
		"Awesomplete",
		"Sortable",
		"Showdown",
		"Taggle",
		"Gantt",
		"Slick",
		"Webcam",
		"PhotoSwipe",
		"PhotoSwipeUI_Default",
		"io",
		"JsBarcode",
		"L",
		"Chart",
		"DataTable",
		"Cypress",
		"cy",
		"it",
		"describe",
		"expect",
		"context",
		"before",
		"beforeEach",
		"after",
		"qz",
		"localforage",
		"extend_cscript",
	].map((name) => [name, "writable"])
);

export default [
	{
		ignores: ["**/public/dist/**", "**/node_modules/**"],
	},
	js.configs.recommended,
	{
		languageOptions: {
			ecmaVersion: 2022,
			sourceType: "module",
			globals: {
				...globals.browser,
				...globals.node,
				...frappeGlobals,
			},
		},
		rules: {
			"no-control-regex": "off",
			"no-extra-boolean-cast": "off",
			"no-unused-vars": "off",
			"no-useless-escape": "off",
		},
	},
];
